In [1]:
import numpy as np
import os
import time
import pickle
import cv2
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from keras import backend as K
from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras.models import Sequential, Model, load_model 
from keras.layers import Dropout, Flatten, Dense, GlobalAveragePooling2D, Input
from keras import backend as k 
from keras.callbacks import ModelCheckpoint, LearningRateScheduler, TensorBoard, EarlyStopping
from keras.optimizers import Adam, RMSprop, SGD
from keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from skimage.transform import resize
from sklearn.svm import SVC

Using TensorFlow backend.


In [2]:
labels = []
feature_list = []
feature_dict=pickle.load(open('features_till_flatten_validation.pkl','rb'))
names = [0,1]
for cat,features  in feature_dict.items():
    labels.extend([int(cat)] * len(features))
    feature_list.append(features)
feature_list = np.concatenate(feature_list)

In [3]:
feature_dict

{0: [array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 8.1864835e+26,
          0.0000000e+00, 4.5168163e+26]], dtype=float32),
  array([[0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 8.616344e+26,
          0.000000e+00, 4.747363e+26]], dtype=float32),
  array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 8.2469150e+26,
          0.0000000e+00, 4.5470527e+26]], dtype=float32),
  array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 7.4126500e+26,
          0.0000000e+00, 4.1074653e+26]], dtype=float32),
  array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 8.6307084e+26,
          0.0000000e+00, 4.7586188e+26]], dtype=float32),
  array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 7.8138475e+26,
          0.0000000e+00, 4.3170919e+26]], dtype=float32),
  array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 8.4641867e+26,
          0.0000000e+00, 4.6696357e+26]], dtype=float32),
  array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 7.7143155e+2

In [4]:
feature_list1=[]
for i in range(0,len(feature_list)):
    feature_list1.append(feature_list[i].ravel())

In [5]:
clf = SVC(kernel='rbf', probability=True).fit(feature_list1,labels )

/usr/local/lib/python3.5/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [6]:
count=0
for i in feature_list:
    print("Prediction : "+str(clf.predict(i)[0]),end='')
    print("   Actual is : "+str(labels[count]))
    count=count+1

Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 0   Actual is : 0
Prediction : 1   Actual is : 1
Prediction : 1   Actual is : 1
Prediction : 1   Actual is : 1
Prediction : 1   Actual is : 1
Prediction : 1   Actual is : 1
Prediction : 1   Actual is : 1
Predicti